# Generated by Django 5.2.4 on 2025-08-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='plat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plats/'),
        ),
    ]
